# Makefile for Terra Text Editor

# Compiler
CC = gcc

# Source files
SRC = main.c
HD = utilities/utilities.c

# Output executable
OUTPUT = ../build/terrate

$(OUTPUT): $(SRC)
	$(CC) $(SRC) $(HD) -o $(OUTPUT) 
